from app.database import Base  # noqa: F401

# Import all models so SQLAlchemy registers them
from app.models.role import Role  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.patient import Patient  # noqa: F401
from app.models.provider import Provider  # noqa: F401
from app.models.claim import Claim  # noqa: F401
from app.models.claim_line_item import ClaimLineItem  # noqa: F401
from app.models.claim_status import ClaimStatusHistory  # noqa: F401
from app.models.claim_payment import ClaimPayment  # noqa: F401
from app.models.claim_attachment import ClaimAttachment  # noqa: F401
from app.models.claim_diagnosis import ClaimDiagnosis  # noqa: F401
from app.models.claim_procedure import ClaimProcedure  # noqa: F401
from app.models.claim_edit import ClaimEdit  # noqa: F401
from app.models.investigation import Investigation  # noqa: F401
from app.models.finding import Finding  # noqa: F401
from app.models.evidence import Evidence  # noqa: F401
from app.models.decision import Decision  # noqa: F401
from app.models.risk import RiskScore  # noqa: F401
from app.models.anomaly import Anomaly  # noqa: F401
from app.models.audit import AuditLog  # noqa: F401
from app.models.notification import Notification  # noqa: F401
from app.models.workflow_task import WorkflowTask  # noqa: F401
from app.models.report import Report  # noqa: F401
from app.models.escalation import Escalation  # noqa: F401
from app.models.resolution import Resolution  # noqa: F401
from app.models.supervisor_review import SupervisorReview  # noqa: F401
from app.models.investigation_event import InvestigationEvent  # noqa: F401
from app.models.investigation_run import InvestigationRun  # noqa: F401
from app.models.agent_execution import AgentExecution  # noqa: F401
from app.models.ai_model import AIModel  # noqa: F401
from app.models.fraud_pattern import FraudPattern  # noqa: F401
from app.models.policy_rule import PolicyRule  # noqa: F401
from app.models.rule_evaluation import RuleEvaluation  # noqa: F401
from app.models.knowledge import KnowledgeArticle  # noqa: F401
from app.models.retrieval import Retrieval  # noqa: F401
from app.models.rag_evaluation import RAGEvaluation  # noqa: F401
from app.models.chat import ChatSession  # noqa: F401
from app.models.copilot import CopilotAction  # noqa: F401
from app.models.session import UserSession  # noqa: F401
from app.models.permission import Permission  # noqa: F401
from app.models.provider_network import ProviderNetwork  # noqa: F401
from app.models.related_claim import RelatedClaim  # noqa: F401
from app.models.referral import Referral  # noqa: F401
from app.models.case_document import CaseDocument  # noqa: F401
from app.models.documentation_request import DocumentationRequest  # noqa: F401
